// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectsTracker.Models;

#nullable disable

namespace ProjectsTracker.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    partial class EmployeesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectsTracker.Models.Employees", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"), 1L, 1);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("RecordID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            RecordID = 1,
                            Company = "IBM",
                            Name = "Ankur",
                            Project = "Payroll",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            RecordID = 2,
                            Company = "IBM",
                            Name = "Akash",
                            Project = "Chatbot",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            RecordID = 3,
                            Company = "HP",
                            Name = "Priya",
                            Project = "VR Gaming",
                            Role = "Project Manager"
                        },
                        new
                        {
                            RecordID = 4,
                            Company = "Microsoft",
                            Name = "Asha",
                            Project = "Payroll",
                            Role = "Solutions Architect"
                        },
                        new
                        {
                            RecordID = 5,
                            Company = "HP",
                            Name = "Nandini",
                            Project = "Payroll",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            RecordID = 6,
                            Company = "Microsoft",
                            Name = "Piyush",
                            Project = "Payroll",
                            Role = "Delivery Manager"
                        },
                        new
                        {
                            RecordID = 7,
                            Company = "HP",
                            Name = "Ankur",
                            Project = "Chatbot",
                            Role = "Lead Engineer"
                        },
                        new
                        {
                            RecordID = 8,
                            Company = "HP",
                            Name = "Akash",
                            Project = "VR Gaming",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            RecordID = 9,
                            Company = "IBM",
                            Name = "Priya",
                            Project = "Payroll",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            RecordID = 10,
                            Company = "HP",
                            Name = "Asha",
                            Project = "Chatbot",
                            Role = "Delivery Manager"
                        },
                        new
                        {
                            RecordID = 11,
                            Company = "IBM",
                            Name = "Nandini",
                            Project = "VR Gaming",
                            Role = "Lead Engineer"
                        },
                        new
                        {
                            RecordID = 12,
                            Company = "Microsoft",
                            Name = "Piyush",
                            Project = "Chatbot",
                            Role = "Delivery Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
